export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const CLEAR_VALUES = 'CLEAR_VALUES';

//Item Management
export const CREATE_ITEM_BEGIN = 'CREATE_ITEM_BEGIN';
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS';
export const CREATE_ITEM_ERROR = 'CREATE_ITEM_ERROR';

export const GET_ITEMS_BEGIN = 'GET_ITEMS_BEGIN';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';

export const SET_EDIT_ITEM = 'SET_EDIT_ITEM';

export const DELETE_ITEM_BEGIN = 'DELETE_ITEM_BEGIN';
export const DELETE_ITEM_ERROR = 'DELETE_ITEM_ERROR';

export const EDIT_ITEM_BEGIN = 'EDIT_ITEM_BEGIN';
export const EDIT_ITEM_SUCCESS = 'EDIT_ITEM_SUCCESS';
export const EDIT_ITEM_ERROR = 'EDIT_ITEM_ERROR';

//Customer Management
export const CREATE_CUSTOMER_BEGIN = 'CREATE_CUSTOMER_BEGIN';
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
export const CREATE_CUSTOMER_ERROR = 'CREATE_CUSTOMER_ERROR';

export const GET_CUSTOMERS_BEGIN = 'GET_CUSTOMERS_BEGIN';
export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS';

export const SET_EDIT_CUSTOMER = 'SET_EDIT_CUSTOMER';

export const DELETE_CUSTOMER_BEGIN = 'DELETE_CUSTOMER_BEGIN';
export const DELETE_CUSTOMER_ERROR = 'DELETE_CUSTOMER_ERROR';

export const EDIT_CUSTOMER_BEGIN = 'EDIT_CUSTOMER_BEGIN';
export const EDIT_CUSTOMER_SUCCESS = 'EDIT_CUSTOMER_SUCCESS';
export const EDIT_CUSTOMER_ERROR = 'EDIT_CUSTOMER_ERROR';

//Payment Management
export const CREATE_PAYMENT_BEGIN = 'CREATE_PAYMENT_BEGIN';
export const CREATE_PAYMENT_SUCCESS = 'CREATE_PAYMENT_SUCCESS';
export const CREATE_PAYMENT_ERROR = 'CREATE_PAYMENT_ERROR';

export const GET_PAYMENTS_BEGIN = 'GET_PAYMENTS_BEGIN';
export const GET_PAYMENTS_SUCCESS = 'GET_PAYMENTS_SUCCESS';

export const SET_EDIT_PAYMENT = 'SET_EDIT_PAYMENT';

export const DELETE_PAYMENT_BEGIN = 'DELETE_PAYMENT_BEGIN';
export const DELETE_PAYMENT_ERROR = 'DELETE_PAYMENT_ERROR';

export const EDIT_PAYMENT_BEGIN = 'EDIT_PAYMENT_BEGIN';
export const EDIT_PAYMENT_SUCCESS = 'EDIT_PAYMENT_SUCCESS';
export const EDIT_PAYMENT_ERROR = 'EDIT_PAYMENT_ERROR';

//Supplier Management
export const CREATE_SUPPLIER_BEGIN = 'CREATE_SUPPLIER_BEGIN';
export const CREATE_SUPPLIER_SUCCESS = 'CREATE_SUPPLIER_SUCCESS';
export const CREATE_SUPPLIER_ERROR = 'CREATE_SUPPLIER_ERROR';

export const GET_SUPPLIERS_BEGIN = 'GET_SUPPLIERS_BEGIN';
export const GET_SUPPLIERS_SUCCESS = 'GET_SUPPLIERS_SUCCESS';

export const SET_EDIT_SUPPLIER = 'SET_EDIT_SUPPLIER';

export const DELETE_SUPPLIER_BEGIN = 'DELETE_SUPPLIER_BEGIN';
export const DELETE_SUPPLIER_ERROR = 'DELETE_SUPPLIER_ERROR';

export const EDIT_SUPPLIER_BEGIN = 'EDIT_SUPPLIER_BEGIN';
export const EDIT_SUPPLIER_SUCCESS = 'EDIT_SUPPLIER_SUCCESS';
export const EDIT_SUPPLIER_ERROR = 'EDIT_SUPPLIER_ERROR';

//Repairs
export const CREATE_REPAIR_BEGIN = 'CREATE_REPAIR_BEGIN';
export const CREATE_REPAIR_SUCCESS = 'CREATE_REPAIR_SUCCESS';
export const CREATE_REPAIR_ERROR = 'CREATE_REPAIR_ERROR';

export const GET_REPAIRS_BEGIN = 'GET_REPAIRS_BEGIN';
export const GET_REPAIRS_SUCCESS = 'GET_REPAIRS_SUCCESS';

export const SET_EDIT_REPAIR = 'SET_EDIT_REPAIR';

export const DELETE_REPAIR_BEGIN = 'DELETE_REPAIR_BEGIN';
export const DELETE_REPAIR_ERROR = 'DELETE_REPAIR_ERROR';

export const EDIT_REPAIR_BEGIN = 'EDIT_REPAIR_BEGIN';
export const EDIT_REPAIR_SUCCESS = 'EDIT_REPAIR_SUCCESS';
export const EDIT_REPAIR_ERROR = 'EDIT_REPAIR_ERROR';

//Delivery
export const CREATE_DELIVERY_BEGIN = 'CREATE_DELIVERY_BEGIN';
export const CREATE_DELIVERY_SUCCESS = 'CREATE_DELIVERY_SUCCESS';
export const CREATE_DELIVERY_ERROR = 'CREATE_DELIVERY_ERROR';

export const GET_DELIVERIES_BEGIN = 'GET_DELIVERIES_BEGIN';
export const GET_DELIVERIES_SUCCESS = 'GET_DELIVERIES_SUCCESS';

export const SET_EDIT_DELIVERY = 'SET_EDIT_DELIVERY';

export const DELETE_DELIVERY_BEGIN = 'DELETE_DELIVERY_BEGIN';
export const DELETE_DELIVERY_ERROR = 'DELETE_DELIVERY_ERROR';

export const EDIT_DELIVERY_BEGIN = 'EDIT_DELIVERY_BEGIN';
export const EDIT_DELIVERY_SUCCESS = 'EDIT_DELIVERY_SUCCESS';
export const EDIT_DELIVERY_ERROR = 'EDIT_DELIVERY_ERROR';

//Employee
export const CREATE_EMPLOYEE_BEGIN = 'CREATE_EMPLOYEE_BEGIN';
export const CREATE_EMPLOYEE_SUCCESS = 'CREATE_EMPLOYEE_SUCCESS';
export const CREATE_EMPLOYEE_ERROR = 'CREATE_EMPLOYEE_ERROR';

export const GET_EMPLOYEES_BEGIN = 'GET_EMPLOYEES_BEGIN';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';

export const SET_EDIT_EMPLOYEE = 'SET_EDIT_EMPLOYEE';

export const DELETE_EMPLOYEE_BEGIN = 'DELETE_EMPLOYEE_BEGIN';
export const DELETE_EMPLOYEE_ERROR = 'DELETE_EMPLOYEE_ERROR';

export const EDIT_EMPLOYEE_BEGIN = 'EDIT_EMPLOYEE_BEGIN';
export const EDIT_EMPLOYEE_SUCCESS = 'EDIT_EMPLOYEE_SUCCESS';
export const EDIT_EMPLOYEE_ERROR = 'EDIT_EMPLOYEE_ERROR';


//Warranty Management
export const CREATE_WARRANTY_BEGIN = 'CREATE_WARRANTY_BEGIN';
export const CREATE_WARRANTY_SUCCESS = 'CREATE_WARRANTY_SUCCESS';
export const CREATE_WARRANTY_ERROR = 'CREATE_WARRANTY_ERROR';

export const GET_WARRANTIES_BEGIN = 'GET_WARRANTIES_BEGIN';
export const GET_WARRANTIES_SUCCESS = 'GET_WARRANTIES_SUCCESS';

export const SET_EDIT_WARRANTY = 'SET_EDIT_WARRANTY';

export const DELETE_WARRANTY_BEGIN = 'DELETE_WARRANTY_BEGIN';
export const DELETE_WARRANTY_ERROR = 'DELETE_WARRANTY_ERROR';

export const EDIT_WARRANTY_BEGIN = 'EDIT_WARRANTY_BEGIN';
export const EDIT_WARRANTY_SUCCESS = 'EDIT_WARRANTY_SUCCESS';
export const EDIT_WARRANTY_ERROR = 'EDIT_WARRANTY_ERROR';

//ori ekn cppy krla gtte
export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN';
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const CHANGE_PAGE = 'CHANGE_PAGE';

export const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';

/////////////////////////

export const SET_REPAIR_ITEM = 'SET_REPAIR_ITEM';